# Generated by Django 5.2.7 on 2025-11-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_option_userselection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userselection',
            name='option',
        ),
        migrations.RemoveField(
            model_name='userselection',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='desired_job',
            field=models.CharField(blank=True, choices=[('프론트엔드', '프론트엔드'), ('백엔드', '백엔드'), ('데이터', '데이터'), ('디자인', '디자인'), ('기획/PM', '기획/PM'), ('DevOps', 'DevOps')], max_length=30, null=True, verbose_name='희망 직무'),
        ),
        migrations.AddField(
            model_name='user',
            name='spec_job',
            field=models.CharField(blank=True, choices=[('프론트엔드', '프론트엔드'), ('백엔드', '백엔드'), ('데이터', '데이터'), ('디자인', '디자인'), ('기획/PM', '기획/PM'), ('DevOps', 'DevOps')], max_length=30, null=True, verbose_name='보유 스펙'),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='UserSelection',
        ),
    ]
