# Generated by Django 5.2.8 on 2025-11-11 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userselection_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='field',
        ),
    ]
