# Generated by Django 5.2.7 on 2025-11-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='desired_job',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='join_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rating_avg',
        ),
        migrations.RemoveField(
            model_name='user',
            name='resume_link',
        ),
        migrations.RemoveField(
            model_name='user',
            name='spec_job',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_reviews',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='agree_ad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='agree_age',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='agree_personal_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='agree_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', '여자'), ('male', '남자')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('mentee', '일반'), ('mentor', '멘토'), ('company', '기업')], max_length=10),
        ),
    ]
