# Generated by Django 5.2.7 on 2025-12-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='회사명'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_type',
            field=models.CharField(blank=True, choices=[('대기업', '대기업'), ('중견기업', '중견기업'), ('중소기업', '중소기업'), ('외국계', '외국계'), ('공기업', '공기업'), ('벤처기업', '벤처기업')], max_length=20, null=True, verbose_name='기업형태'),
        ),
        migrations.AddField(
            model_name='user',
            name='experience_years',
            field=models.IntegerField(default=0, verbose_name='경력'),
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, choices=[('개발', '개발'), ('데이터', '데이터'), ('인공지능/머신러닝', '인공지능/머신러닝'), ('디자인', '디자인'), ('QA/테스트', 'QA/테스트')], max_length=50, null=True, verbose_name='직무'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_detail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='세부 직무'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_level',
            field=models.CharField(blank=True, choices=[('신입', '신입'), ('주임', '주임'), ('대리', '대리'), ('과장', '과장'), ('차장', '차장'), ('부장', '부장'), ('임원', '임원')], max_length=20, null=True, verbose_name='직급'),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='근무지역'),
        ),
    ]
